url: "https://xerolux.github.io"
baseurl: "/modbridge"
theme: jekyll-theme-cayman
title: ModBridge Documentation
description: Ein moderner, robuster Modbus TCP Proxy Manager mit eleganter Web-Oberfläche.
